version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15

    working_directory: ~/repo

    steps:
      - checkout

      - deploy:
          name: Deploy to Now
          command: |
            GIT_HASH=$(git rev-parse --short HEAD)
            SANITIZED_BRANCH=$(tr "/" "-" <<<$CIRCLE_BRANCH)
            VERY_SANITIZED_BRANCH=$(tr "." "-" <<<$SANITIZED_BRANCH)
            echo ${GIT_HASH} > version
            BUILD_URL=$(npx now --name hq.mybit.io -t $NOW_DEVELOPMENT_TOKEN --public)
            npx now alias ${BUILD_URL} \
            ${GIT_HASH}-hq-mybit-io-dev -t \
            $NOW_DEVELOPMENT_TOKEN
            npx now alias ${BUILD_URL} \
            ${VERY_SANITIZED_BRANCH}-hq-mybit-io-dev -t \
            $NOW_DEVELOPMENT_TOKEN